In [14]:
#matriz es un arreglo que esta compusto por filas y columnas de un mismo tipo de dato en este caso numerico 
#primero la fila y luego la columna 

#desarrollo ejercicios propuestos en img de excel
import numpy as np

b=np.array([[1],[2],[3],[4]])
print(b.shape)
print(b)

c=np.array([[1],[2],[3]])
print(c.shape)
print(c)

d=np.array([[4],[3],[2],[4],[3],[1]])
print(d.shape)
print(d)

e=np.array(([1,2,3],[1,2,3]))
print(e.shape)
print(e)

f=np.array(([1,2],[1,2],[1,2],[1,2],[1,2]))
print(f.shape)

a=4*np.eye(4)
print(a)
print(a.shape)

z=np.eye(4)
print(z)
print(z.shape)
print(4*z.shape)






(4, 1)
[[1]
 [2]
 [3]
 [4]]
(3, 1)
[[1]
 [2]
 [3]]
(6, 1)
[[4]
 [3]
 [2]
 [4]
 [3]
 [1]]
(2, 3)
[[1 2 3]
 [1 2 3]]
(5, 2)
[[4. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
(4, 4, 4, 4, 4, 4, 4, 4)


In [15]:
! conda install pandas

^C


In [1]:
a=1+2
print(a)

3


**Python**